run2            DATA - 42
run2               I - 29
run2            SIZE - 27
run2             THE - 26
run2               T - 25
run2            UINT - 21
run2             END - 19
run2              OF - 18
run2            WORD - 18
run2               S - 16
run2              WC - 16
run2               A - 13
run2           CONST - 12
run2            CHAR - 11
run2           CHECK - 10
run2           ERROR - 10
run2           FINFO - 10
run2               H - 10
run2             MAP - 10
run2              OR - 10
run2          RESULT - 10
run2          RETURN - 10
run2             AND - 9
run2            DISP - 9
run2           ENDIF - 9
run2           FDATA - 9
run2             NUM - 9
run2            TIME - 9
run2             FOR - 8
run2             GET - 8
run2            HASH - 8
run2              ST - 8
run2              TO - 8
run2           BEGIN - 7
run2              FD - 7
run2            FILE - 7
run2           IFDEF - 7
run2              IN - 7
run2         INCLUDE - 7
run2             INT - 7
run2             LEN - 7
run2               N - 7
run2             OUT - 7
run2             POS - 7
run2          PRINTF - 7
run2        SPLITTER - 7
run2         WORDSMR - 7
run2             KEY - 6
run2            MMAP - 6
run2            NULL - 6
run2               R - 6
run2             STR - 6
run2            THIS - 6
run2             VAL - 6
run2           WHILE - 6
run2            ARGV - 5
run2           CHUNK - 5
run2           OTHER - 5
run2          STRING - 5
run2          STRUCT - 5
run2             USE - 5
run2       WORDCOUNT - 5
run2             ANY - 4
run2               B - 4
run2            ELSE - 4
run2              IF - 4
run2       MAPREDUCE - 4
run2              NO - 4
run2        STANFORD - 4
run2           START - 4
run2             TBB - 4
run2           TOTAL - 4
run2      UNIVERSITY - 4
run2               V - 4
run2             ARE - 3
run2            BOOL - 3
run2      CONDITIONS - 3
run2       CONTAINER - 3
run2       COPYRIGHT - 3
run2              DN - 3
run2           FNAME - 3
run2       FOLLOWING - 3
run2       INCLUDING - 3
run2              IS - 3
run2          KEYVAL - 3
run2          LENGTH - 3
run2              LU - 3
run2          MEMORY - 3
run2            MUST - 3
run2        OPERATOR - 3
run2           PRINT - 3
run2        PROVIDED - 3
run2          PUBLIC - 3
run2            READ - 3
run2         RESULTS - 3
run2        SOFTWARE - 3
run2             STD - 3
run2          STRCMP - 3
run2          TIMING - 3
run2        UNSIGNED - 3
run2              A' - 2
run2           ABOVE - 2
run2       ALLOCATOR - 2
run2              AS - 2
run2              BE - 2
run2          BINARY - 2
run2             BUT - 2
run2           CLASS - 2
run2        COMBINER - 2
run2         DEFAULT - 2
run2          DEFINE - 2
run2      DISCLAIMER - 2
run2         DISPLAY - 2
run2        FILENAME - 2
run2           FIXED - 2
run2            FROM - 2
run2          IFNDEF - 2
run2         IMPLIED - 2
run2       LIABILITY - 2
run2         LIMITED - 2
run2            LIST - 2
run2   MAPREDUCESORT - 2
run2             MIN - 2
run2            NEXT - 2
run2             NOT - 2
run2          NOTICE - 2
run2              ON - 2
run2           POINT - 2
run2        POPULATE - 2
run2         PRIVATE - 2
run2            PROT - 2
run2 REDISTRIBUTIONS - 2
run2          REDUCE - 2
run2        SCALABLE - 2
run2          SOURCE - 2
run2           SPLIT - 2
run2            STAT - 2
run2             SUM - 2
run2             SYS - 2
run2             TOP - 2
run2            TYPE - 2
run2             ULL - 2
run2            VOID - 2
run2      WARRANTIES - 2
run2            WITH - 2
run2         WITHOUT - 2
run2              Z' - 2
run2         ADVISED - 1
run2             ALL - 1
run2            ARGC - 1
run2         ARISING - 1
run2            ATOI - 1
run2            BITS - 1
run2          BORDER - 1
run2           BREAK - 1
run2        BUSINESS - 1
run2              BY - 1
run2               C - 1
run2         CALLING - 1
run2          CAUSED - 1
run2           CLOSE - 1
run2            CODE - 1
run2       COMPLETED - 1
run2   CONSEQUENTIAL - 1
run2        CONTRACT - 1
run2    CONTRIBUTORS - 1
run2           CTYPE - 1
run2               D - 1
run2          DAMAGE - 1
run2         DAMAGES - 1
run2         DERIVED - 1
run2       DETERMINE - 1
run2          DIRECT - 1
run2      DISCLAIMED - 1
run2    DISTRIBUTION - 1
run2          DIVIDE - 1
run2   DOCUMENTATION - 1
run2               E - 1
run2            EMIT - 1
run2         ENDORSE - 1
run2            EVEN - 1
run2           EVENT - 1
run2       EXEMPLARY - 1
run2            EXIT - 1
run2        EXPLICIT - 1
run2         EXPRESS - 1
run2           FALSE - 1
run2           FCNTL - 1
run2        FINALIZE - 1
run2         FITNESS - 1
run2             FNV - 1
run2            FORM - 1
run2           FORMS - 1
run2            FREE - 1
run2           FSTAT - 1
run2       FUNCTIONS - 1
run2           GOODS - 1
run2         HOWEVER - 1
run2      INCIDENTAL - 1
run2        INDIRECT - 1
run2            INFO - 1
run2      INITIALIZE - 1
run2           INPUT - 1
run2    INTERMEDIATE - 1
run2    INTERRUPTION - 1
run2            IS'' - 1
run2             ITS - 1
run2          LIABLE - 1
run2         LIBRARY - 1
run2          LOCATE - 1
run2            LOSS - 1
run2            MAIN - 1
run2            MAKE - 1
run2          MALLOC - 1
run2       MATERIALS - 1
run2             MAY - 1
run2 MERCHANTABILITY - 1
run2             MET - 1
run2            MMAN - 1
run2    MODIFICATION - 1
run2            MOVE - 1
run2          MUNMAP - 1
run2              N' - 1
run2            NAME - 1
run2           NAMES - 1
run2       NECESSARY - 1
run2      NEGLIGENCE - 1
run2         NEITHER - 1
run2         NOMINAL - 1
run2             NOR - 1
run2          NUMBER - 1
run2      NWORDCOUNT - 1
run2               O - 1
run2            OPEN - 1
run2       OTHERWISE - 1
run2      PARTICULAR - 1
run2         PASSAGE - 1
run2      PERMISSION - 1
run2       PERMITTED - 1
run2     POSSIBILITY - 1
run2           PREAD - 1
run2           PRIOR - 1
run2     PROCUREMENT - 1
run2        PRODUCTS - 1
run2         PROFITS - 1
run2         PROMOTE - 1
run2         PURPOSE - 1
run2              R' - 1
run2          RDONLY - 1
run2         REACHED - 1
run2  REDISTRIBUTION - 1
run2       REPRODUCE - 1
run2        RESERVED - 1
run2          RETAIN - 1
run2          RIGHTS - 1
run2             RUN - 1
run2         RUNNING - 1
run2       SCHEDULER - 1
run2        SERVICES - 1
run2             SET - 1
run2           SHALL - 1
run2           SINCE - 1
run2          SINGLE - 1
run2     SMARTINDENT - 1
run2        SMARTTAB - 1
run2            SORT - 1
run2           SPACE - 1
run2         SPECIAL - 1
run2        SPECIFIC - 1
run2       SPECIFIED - 1
run2          STRICT - 1
run2             STS - 1
run2      SUBSTITUTE - 1
run2            SUCH - 1
run2            SURE - 1
run2              SW - 1
run2              T' - 1
run2      TERMINATED - 1
run2            TEXT - 1
run2            THAT - 1
run2          THEORY - 1
run2        TIMESPEC - 1
run2            TORT - 1
run2         TOUPPER - 1
run2            TRUE - 1
run2              TS - 1
run2           USAGE - 1
run2            USED - 1
run2           VALID - 1
run2          VECTOR - 1
run2             VIM - 1
run2             WAY - 1
run2         WHETHER - 1
run2         WRITTEN - 1
